service: graphscript-lambda
provider:
  name: aws
  runtime: nodejs12.x
  profile: huy
  stage: dev

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true