jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: kciter/aws-ecr-action@master
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: http://471226395362.dkr.ecr.us-east-1.amazonaws.com/graphscipt-container
        region: us-west-2
        tags: latest,${{ github.sha }}
        create_repo: true
